### PR TITLE
Custom user scripts.

### PR DESCRIPTION
**Pull request by w3e**

### CODE REVIEW

**Comment by ivan-gomes** [comment]
Please refactor MDKOptionsGroup#USER_SCRIPT_DIRECTORY to USER_SCRIPT_DIRECTORIES for consistency.

**Comment by w3e** [comment]
Refactoring done.

**Comment by ivan-gomes** [comment]
Please reset the default for MDK Advanced Options.

**Comment by w3e** [comment]
Do you mean set it to false? Currently it sets to true.

**Pull request merged**
