### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by borromeotlhs**
Some changes that aren't reflected in the user manual or in setup documents.

### CODE REVIEW

**Comment by ivan-gomes** [comment]
Is this applicable to MagicDraw 18.5 and Java 8?

**Comment by borromeotlhs** [comment]
I'm on magic draw 18.4, but am using the 8 series of the jdk. so. . . dunno ;)

**Comment by ivan-gomes** [comment]
By my understanding this property is not necessary for properly configured servers (source: https://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0/14884941#14884941). Can you please confirm you are trying to workaround the exception reported in the OP of the source?

**Comment by borromeotlhs** [comment]
no idea, but again, I'd err that perhaps this be a note rather than a necessity as I can't even recall how I encountered this error.

**Comment by ivan-gomes** [comment]
I only ask, because there could be a way to do this without requiring user intervention. I have added
`System.setProperty("jsse.enableSNIExtension", "false");` to the initialization of the MDK plugin in 3.0.0 (and moving forward). I expect that this will resolve this issue. However it will still apply to previous versions of MDK, so I think it would be helpful to add it to the README of the support/2.5 branch. Feel free to make a pull request for that.

**Pull request closed without merging**
